name: Validate site
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Link checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress --verbose --max-concurrency 4 --exclude-mail --accept 200,206,429 --index index.html .

      - name: HTML5 validator
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: .
          blacklist: ".git,_headers"
          css: true
          html: true